### ISSUE TITLE
Crash when selecting submission title

### ISSUE THREAD

**Issue by Tunous** [Tunous/Dawn#190]
**Describe the bug**
Application crashed after attempting to select submission title.

**To Reproduce**
1. Go to any submission
2. Long press on submission title to select it

**Expected behavior**
Submission title is selected

**Additional context**

<details>
<summary>Stack-trace</summary>

```
FATAL EXCEPTION: main
Process: me.thanel.dank, PID: 10313
java.lang.IndexOutOfBoundsException: setSpan (-1 ... -1) starts before 0
	at android.text.SpannableStringInternal.checkRange(SpannableStringInternal.java:434)
	at android.text.SpannableStringInternal.setSpan(SpannableStringInternal.java:155)
	at android.text.SpannableString.setSpan(SpannableString.java:46)
	at android.text.Selection.setSelection(Selection.java:76)
	at me.saket.dank.widgets.SelectionLimitingTextView.onSelectionChanged(SelectionLimitingTextView.kt:48)
	at android.widget.TextView.spanChange(TextView.java:8307)
	at android.widget.TextView$ChangeWatcher.onSpanRemoved(TextView.java:10404)
	at android.text.SpannableStringInternal.sendSpanRemoved(SpannableStringInternal.java:400)
	at android.text.SpannableStringInternal.removeSpan(SpannableStringInternal.java:235)
	at android.text.SpannableString.removeSpan(SpannableString.java:50)
	at android.text.Selection.removeSelection(Selection.java:109)
	at me.saket.dank.widgets.SelectionLimitingTextView.onSelectionChanged(SelectionLimitingTextView.kt:46)
	at android.widget.TextView.spanChange(TextView.java:8307)
	at android.widget.TextView$ChangeWatcher.onSpanChanged(TextView.java:10392)
	at android.text.SpannableStringInternal.sendSpanChanged(SpannableStringInternal.java:410)
	at android.text.SpannableStringInternal.setSpan(SpannableStringInternal.java:190)
	at android.text.SpannableString.setSpan(SpannableString.java:46)
	at android.text.Selection.setSelection(Selection.java:78)
	at android.widget.Editor.selectCurrentWord(Editor.java:865)
	at android.widget.Editor.selectCurrentWordAndStartDrag(Editor.java:1966)
	at android.widget.Editor.performLongClick(Editor.java:1124)
	at android.widget.TextView.performLongClick(TextView.java:9420)
	at android.view.View.performLongClick(View.java:5690)
	at android.view.View$CheckForLongPress.run(View.java:22398)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6121)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```

</details>

**Comment by Tunous** [comment]
@AbsurdlySuspicious you might want to look int it. The crash happened when google bot which automatically tests application attempted to select submission title. I don’t know if it does selection in an unusual way but it’s worth taking a look.

I can share a video if needed but we can’t see a lot from it.

**Comment by AbsurdlySuspicious** [comment]
I was able to reproduce this only artificially, but fix is pretty trivial anyway. I will submit a PR
