### ISSUE TITLE
Unable to start receiver me.saket.dank.notifs.MediaNotifActionReceiver

### ISSUE THREAD

**Issue by Tunous** [Tunous/Dawn#191]
**Describe the bug**
Not much info here just a stack trace from a crash.

**To Reproduce**
1. ???

**Expected behavior**
Application doesn’t crash :)

**Smartphone (please complete the following information):**
- brand: Xiaomi
- dpi: 408
- locale: en_IN
- model: Mi MIX 2
- orientation: portrait
- osName: android
- osVersion: 9
- screenDensity: 2.55
- screenResolution: 2040x1080

**Additional context**

<details>
<summary>TITLE</summary>

```
java.lang.RuntimeException: Unable to start receiver me.saket.dank.notifs.MediaNotifActionReceiver: android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
        at android.app.ActivityThread.handleReceiver(ActivityThread.java:3460)
        at android.app.ActivityThread.access$1300(ActivityThread.java:202)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1691)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:6878)
        at java.lang.reflect.Method.invoke(Method.java:-2)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)

Caused by: android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
        at android.app.ContextImpl.startActivity(ContextImpl.java:922)
        at android.app.ContextImpl.startActivity(ContextImpl.java:898)
        at android.content.ContextWrapper.startActivity(ContextWrapper.java:389)
        at android.content.ContextWrapper.startActivity(ContextWrapper.java:389)
        at me.saket.dank.notifs.MediaNotifActionReceiver.onReceive(MediaNotifActionReceiver.java:63)
        at android.app.ActivityThread.handleReceiver(ActivityThread.java:3451)
        at android.app.ActivityThread.access$1300(ActivityThread.java:202)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1691)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:6878)
        at java.lang.reflect.Method.invoke(Method.java:-2)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)
```

</details>

**Comment by Tunous** [comment]
This is what appeared shortly before. Might be related.

```
1588520009861 I Enqueuing RedditHostedVideoLink{unparsedUrl=https://v.redd.it/tsvwh9xkpjw41, highQualityUrl=https://v.redd.it/tsvwh9xkpjw41/DASHPlaylist.mpd, directUrlWithoutAudio=https://v.redd.it/tsvwh9xkpjw41/DASH_720?source=fallback}

1588520010063 I Recvd request for RedditHostedVideoLink{unparsedUrl=https://v.redd.it/tsvwh9xkpjw41, highQualityUrl=https://v.redd.it/tsvwh9xkpjw41/DASHPlaylist.mpd, directUrlWithoutAudio=https://v.redd.it/tsvwh9xkpjw41/DASH_720?source=fallback}

1588520010066 I Downloading RedditHostedVideoLink{unparsedUrl=https://v.redd.it/tsvwh9xkpjw41, highQualityUrl=https://v.redd.it/tsvwh9xkpjw41/DASHPlaylist.mpd, directUrlWithoutAudio=https://v.redd.it/tsvwh9xkpjw41/DASH_720?source=fallback}

1588520013929 I Stopping service
```
