### ISSUE TITLE
Crash after posting comment reply

### ISSUE THREAD

**Issue by Tunous** [Tunous/Dawn#21]
```
FATAL EXCEPTION: main
Process: me.saket.dank.debug, PID: 4889
java.lang.AssertionError
	at me.saket.dank.ui.submission.adapter.SubmissionLocalComment$ViewHolder.renderPartialChanges(SubmissionLocalComment.kt:120)
	at me.saket.dank.ui.submission.adapter.SubmissionLocalComment$Adapter.onBindViewHolder(SubmissionLocalComment.kt:154)
	at me.saket.dank.ui.submission.adapter.SubmissionLocalComment$Adapter.onBindViewHolder(SubmissionLocalComment.kt:131)
	at me.saket.dank.ui.submission.adapter.SubmissionCommentsAdapter.onBindViewHolder(SubmissionCommentsAdapter.java:127)
	at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6714)
	at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5647)
	at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5913)
	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5752)
	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5748)
	at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2232)
	at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1559)
	at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1519)
	at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:614)
	at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3812)
	at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3529)
	at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:4082)
	at android.view.View.layout(View.java:19692)
	at android.view.ViewGroup.layout(ViewGroup.java:6057)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:19692)
	at android.view.ViewGroup.layout(ViewGroup.java:6057)
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1080)
	at android.view.View.layout(View.java:19692)
	at android.view.ViewGroup.layout(ViewGroup.java:6057)
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1080)
	at me.saket.dank.widgets.InboxUI.IndependentExpandablePageLayout.onLayout(IndependentExpandablePageLayout.java:36)
	at android.view.View.layout(View.java:19692)
	at android.view.ViewGroup.layout(ViewGroup.java:6057)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:19692)
	at android.view.ViewGroup.layout(ViewGroup.java:6057)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
	at android.view.View.layout(View.java:19692)
	at android.view.ViewGroup.layout(ViewGroup.java:6057)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:19692)
	at android.view.ViewGroup.layout(ViewGroup.java:6057)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
	at android.view.View.layout(View.java:19692)
	at android.view.ViewGroup.layout(ViewGroup.java:6057)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:759)
	at android.view.View.layout(View.java:19692)
	at android.view.ViewGroup.layout(ViewGroup.java:6057)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2521)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2230)
```

**Comment by saket** [comment]
I can see a lint warning that I'm comparing two different types in `SubmissionLocalComment#L119`:
https://github.com/saket/Dank/blob/52b2b8b513c8c924b04e2ad806e4b3fe152a3f4a/app/src/main/java/me/saket/dank/ui/submission/adapter/SubmissionLocalComment.kt#L119

It looks like this is the issue.
