### ISSUE TITLE
Navigating to user profile via link does nothing

### ISSUE THREAD

**Issue by Tunous** [Tunous/Dawn#76]
## Error in Dank

**java.lang.RuntimeException** in **UrlRouter.java:64**
Unable to start activity ComponentInfo{me.thanel.dank/me.saket.dank.deeplinks.DeepLinkHandlingActivity}: java.lang.UnsupportedOperationException: Use forLink(RedditUserLink) instead.

[View on Bugsnag](https://app.bugsnag.com/tunous/dank/errors/5d744a688ab3be001a23a6f2?event_id=5d744a68004f3868759e0000&i=gh&m=ci)

## Stacktrace

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{me.thanel.dank/me.saket.dank.deeplinks.DeepLinkHandlingActivity}: java.lang.UnsupportedOperationException: Use forLink(RedditUserLink) instead.
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2951)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3086)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6719)
        at java.lang.reflect.Method.invoke(Method.java:-2)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:495)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: java.lang.UnsupportedOperationException: Use forLink(RedditUserLink) instead.
        at me.saket.dank.ui.UrlRouter.forLink(UrlRouter.java:64)
        at me.saket.dank.deeplinks.DeepLinkHandlingActivity.onCreate(DeepLinkHandlingActivity.java:61)
        at android.app.Activity.performCreate(Activity.java:7144)
        at android.app.Activity.performCreate(Activity.java:7135)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2931)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3086)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6719)
        at java.lang.reflect.Method.invoke(Method.java:-2)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:495)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

[View full stacktrace](https://app.bugsnag.com/tunous/dank/errors/5d744a688ab3be001a23a6f2?event_id=5d744a68004f3868759e0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by Tunous** [comment]
Happens when user tries to navigate to user profile via link from outside of the application. We should display a message that this is currently unsupported and/or redirect the user to browser.

Location of the crash:
https://github.com/Tunous/Dank/blob/master/app/src/main/java/me/saket/dank/deeplinks/DeepLinkHandlingActivity.java#L61
